# Generated by Django 4.2.3 on 2023-07-27 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(max_length=20),
        ),
    ]
