# Generated by Django 4.2.3 on 2023-07-27 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newest', '0002_alter_student_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='admision',
            new_name='admission',
        ),
    ]
